version: "3.8"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb

  frontend:
    build: ./frontend/property-broker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/property-broker-frontend:/app
      # - /app/node_modules
    environment:
      - API_INTERNAL_URL=http://backend:4000
      - NEXT_PUBLIC_API_URL=http://localhost:4000

  # scraper:
  #   # dockerfile: Dockerfile.dev
  #   build: ./scraping-tool
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./scraping-tool:/app
  #   environment:
  #     - DATABASE_URL=postgres://user:password@db:5432/mydb

volumes:
  pgdata: